CareerPortal.MvcWebUI/Areas/JobGiver/Controllers/JobController.cs
using AutoMapper;
using CareerPortal.Core.Dtos.Concrete.JobPost;
using CareerPortal.MvcWebUI.Areas.JobGiver.Models;
using CareerPortal.MvcWebUI.Constants;
using CareerPortal.MvcWebUI.Helper.Alert.AlertifyJs;
using CareerPortal.MvcWebUI.Helper.Api.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Web;

namespace CareerPortal.MvcWebUI.Areas.JobGiver.Controllers
{
    [Area("JobGiver")]
    [Authorize(Roles = OperationClaimNames.Is_Veren)]
    public class JobController : Controller
    {
        private IHomeApiService _homeApiService;
        private IJobGiverJobPostApiService _jobGiverJobPostApiService;
        private readonly IMapper _mapper;
        private IHostingEnvironment _env;

        public JobController(IHomeApiService homeApiService, IJobGiverJobPostApiService jobGiverJobPostApiService, IMapper mapper, IHostingEnvironment env)
        {
            _homeApiService = homeApiService;
            _jobGiverJobPostApiService = jobGiverJobPostApiService;
            _mapper = mapper;
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult PostAJob()
        {
            PostAJobViewModel model = new PostAJobViewModel();
            model.JobFilterComponents = _homeApiService.GetHomeFilterComponents().Data;
            model.GetSectorExperienceYearGenderDtos = _homeApiService.GetSectorExperienceYearGender().Data;
            return View(model);
        }

        [HttpPost]
        public IActionResult PostAJob(PostAJobViewModel model)
        {
            try
            {
                if (model.JobPostImage != null && model.JobPostImage.Length > 0)
                {
                    #region base64string convert
                    //try
                    //{
                    //    using (var ms = new MemoryStream())
                    //    {
                    //        model.JobPostImage.CopyTo(ms);
                    //        var fileBytes = ms.ToArray();
                    //        model.JobPostImageBase64 = Convert.ToBase64String(fileBytes);
                    //        // act on the Base64 data
                    //    }
                    //}
                    //catch
                    //{
                    //    model.JobFilterComponents = _homeApiService.GetHomeFilterComponents().Data;
                    //    model.GetSectorExperienceYearGenderDtos = _homeApiService.GetSectorExperienceYearGender().Data;
                    //    HttpContext.Session.SetString("Alert", AlertifyHelper.ErrorMessage(Messages.ErrorAddJobPost));
                    //    return View(model);
                    //}
                    #endregion
                    string uploadsFolder = Path.Combine(_env.WebRootPath, "jobimages");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.JobPostImage.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.JobPostImage.CopyTo(fileStream);
                    }
                    model.JobPostImageUrl = "/jobimages/" + uniqueFileName;
                }

                if (model.ComponyLogo != null && model.ComponyLogo.Length > 0)
                {
                    #region base64string convert
                    //try
                    //{
                    //    using (var ms = new MemoryStream())
                    //    {
                    //        model.ComponyLogo.CopyTo(ms);
                    //        var fileBytes = ms.ToArray();
                    //        model.ComponyLogoBase64 = Convert.ToBase64String(fileBytes);
                    //        // act on the Base64 data
                    //    }
                    //}
                    //catch
                    //{
                    //    model.JobFilterComponents = _homeApiService.GetHomeFilterComponents().Data;
                    //    model.GetSectorExperienceYearGenderDtos = _homeApiService.GetSectorExperienceYearGender().Data;
                    //    HttpContext.Session.SetString("Alert", AlertifyHelper.ErrorMessage(Messages.ErrorAddJobPost));
                    //    return View(model);
                    //}
                    #endregion
                    string uploadsFolder = Path.Combine(_env.WebRootPath, "companyimages");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ComponyLogo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.ComponyLogo.CopyTo(fileStream);
                    }
                    model.ComponyLogoUrl = "/companyimages/" + uniqueFileName;
                }
            }
            catch (Exception ex)
            {
                //todo: ex
                HttpContext.Session.SetString("Alert", AlertifyHelper.SuccessMessage(Messages.ErrorAddJobPost));
                model.JobFilterComponents = _homeApiService.GetHomeFilterComponents().Data;
                model.GetSectorExperienceYearGenderDtos = _homeApiService.GetSectorExperienceYearGender().Data;
                return View(model);
            }

            model.JobDescription = HttpUtility.HtmlEncode(model.JobDescription);
            model.CompanyDescription = HttpUtility.HtmlEncode(model.CompanyDescription);
            PostAJobViewModelDto dto = _mapper.Map<PostAJobViewModelDto>(model);
            var response = _jobGiverJobPostApiService.JobGiverAddJobPostResponse(dto);
            if (response.Success)
            {
                HttpContext.Session.SetString("Alert", AlertifyHelper.SuccessMessage(Messages.SuccessAddJobPost));
            }
            else
            {
                HttpContext.Session.SetString("Alert", AlertifyHelper.ErrorMessage(Messages.ErrorAddJobPost));
            }
            model.JobFilterComponents = _homeApiService.GetHomeFilterComponents().Data;
            model.GetSectorExperienceYearGenderDtos = _homeApiService.GetSectorExperienceYearGender().Data;
            return View(model);
        }
    }
}

CareerPortal.MvcWebUI/Areas/HomePage/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!doctype html>
<html lang="en">
<head>
    <title>@ViewData["Title"]  JobBoard</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Free-Template.co" />
    <link rel="shortcut icon" href="/jobboard/ftco-32x32.png">

    <link rel="stylesheet" href="/jobboard/css/custom-bs.css">
    <link rel="stylesheet" href="/jobboard/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="/jobboard/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="/jobboard/fonts/icomoon/style.css">
    <link rel="stylesheet" href="/jobboard/fonts/line-icons/style.css">
    <link rel="stylesheet" href="/jobboard/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/jobboard/css/animate.min.css">
    <link rel="stylesheet" href="/jobboard/css/quill.snow.css">
    <link href="~/lib/AlertifyJS/css/alertify.min.css" rel="stylesheet" />
    <link href="~/lib/AlertifyJS/css/themes/default.min.css" rel="stylesheet" />

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/jobboard/css/style.css">
    @RenderSection("Head", false)
</head>
<body id="top">

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>


    <div class="site-wrap">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div> <!-- .site-mobile-menu -->
        <!-- NAVBAR -->
        <header class="site-navbar mt-3">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="site-logo col-6"><a asp-action="Index" asp-controller="Home" asp-area="HomePage">JobBoard</a></div>

                    <nav class="mx-auto site-navigation">
                        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                            <li><a asp-action="About" asp-controller="Home" asp-area="HomePage">Hakkımızda</a></li>
                            <li><a asp-action="Services" asp-controller="Home" asp-area="HomePage">Hizmetler</a></li>
                            <li><a asp-action="Services" asp-controller="Home" asp-area="HomePage">Servisler</a></li>
                            <li><a asp-action="Contact" asp-controller="Home" asp-area="HomePage">İletişim</a></li>
                            @*<li class="has-children">
                                    <a href="job-listings.html">Job Listings</a>
                                    <ul class="dropdown">
                                        <li><a href="job-single.html">Job Single</a></li>
                                        <li><a asp-action="PostAJob" asp-controller="Job" asp-area="JobGiver"><span class="mr-2">+</span> Post a Job</a></li>
                                    </ul>
                                </li>*@
                            @*<li class="has-children">
                                    <a href="services.html">Pages</a>
                                    <ul class="dropdown">
                                        <li><a href="services.html">Services</a></li>
                                        <li><a href="service-single.html">Service Single</a></li>
                                        <li><a href="blog-single.html">Blog Single</a></li>
                                        <li><a href="portfolio.html">Portfolio</a></li>
                                        <li><a href="portfolio-single.html">Portfolio Single</a></li>
                                        <li><a href="testimonials.html">Testimonials</a></li>
                                        <li><a href="faq.html">Frequently Ask Questions</a></li>
                                        <li><a href="gallery.html">Gallery</a></li>
                                    </ul>
                                </li>*@
                            <li><a href="blog.html">Blog</a></li>
                        </ul>
                    </nav>

                    <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                        <div class="ml-auto">
                            <a asp-action="JobGiverLoginSignUp" asp-controller="Home" asp-area="HomePage" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>İş Veren</a>
                            <a asp-action="JobSeekerLoginSignUp" asp-controller="Home" asp-area="HomePage" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>İş Arayan</a>
                        </div>
                        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                    </div>

                </div>
            </div>
        </header>

        @RenderBody()

        <footer class="site-footer">

            <a href="#top" class="smoothscroll scroll-top">
                <span class="icon-keyboard_arrow_up"></span>
            </a>

            <div class="container">
                <div class="row mb-5">
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Search Trending</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Web Design</a></li>
                            <li><a href="#">Graphic Design</a></li>
                            <li><a href="#">Web Developers</a></li>
                            <li><a href="#">Python</a></li>
                            <li><a href="#">HTML5</a></li>
                            <li><a href="#">CSS3</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Company</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Career</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Resources</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Support</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Terms of Service</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Contact Us</h3>
                        <div class="footer-social">
                            <a href="#"><span class="icon-facebook"></span></a>
                            <a href="#"><span class="icon-twitter"></span></a>
                            <a href="#"><span class="icon-instagram"></span></a>
                            <a href="#"><span class="icon-linkedin"></span></a>
                        </div>
                    </div>
                </div>

                <div class="row text-center">
                    <div class="col-12">
                        <p class="copyright">
                            <small>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">JobDream</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    <!-- SCRIPTS -->
    <script src="/jobboard/js/jquery.min.js"></script>
    <script src="/jobboard/js/bootstrap.bundle.min.js"></script>
    <script src="/jobboard/js/isotope.pkgd.min.js"></script>
    <script src="/jobboard/js/stickyfill.min.js"></script>
    <script src="/jobboard/js/jquery.fancybox.min.js"></script>
    <script src="/jobboard/js/jquery.easing.1.3.js"></script>

    <script src="/jobboard/js/jquery.waypoints.min.js"></script>
    <script src="/jobboard/js/jquery.animateNumber.min.js"></script>
    <script src="/jobboard/js/owl.carousel.min.js"></script>
    <script src="/jobboard/js/quill.min.js"></script>

    <script src="/jobboard/js/bootstrap-select.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="/jobboard/js/custom.js"></script>
    <script src="/lib/AlertifyJS/alertify.min.js"></script>
    @RenderSection("Scripts", false)
    @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("Alert")))
    {
        @Html.Raw(HttpContextAccessor.HttpContext.Session.GetString("Alert").ToString())
        HttpContextAccessor.HttpContext.Session.SetString("Alert", "");
    }

</body>
</html>